# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order_gui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDateTime,QTimer,Qt
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import sys
import time

class Ui_Form2(object):
    def setupUi(self, Form):
        pe = QPalette()
        pe.setColor(QPalette.WindowText,Qt.red)
        Form.setObjectName("Form")
        Form.resize(1500, 831)
        self.title = QtWidgets.QLabel(Form)
        self.title.setFont(QFont('DFKai-SB', 36))
        self.title.setGeometry(QtCore.QRect(50, 50, 600, 71))
        self.title.setObjectName("title")
        self.pushButton1 = QtWidgets.QPushButton(Form)
        self.pushButton1.setGeometry(QtCore.QRect(210, 140, 161, 51))
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton1.setFont(QFont('DFKai-SB', 24))
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(30, 490, 600, 271))
        self.textBrowser.setObjectName("textBrowser")
        self.menu = QtWidgets.QLabel(Form)
        self.menu.setGeometry(QtCore.QRect(1300, 10, 171, 61))
        self.menu.setObjectName("menu")
        self.goal = QtWidgets.QLabel(Form)
        self.goal.setFont(QFont('DFKai-SB', 24))
        self.goal.setGeometry(QtCore.QRect(30, 410, 281, 71))
        self.goal.setObjectName("goal")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(450, 90, 721, 721))
        self.label.setText("")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(650, 0, 850, 601))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("1.png"))
        self.label_2.setObjectName("label_2")
        self.time_label = QtWidgets.QLabel(Form)
        self.time_label.setGeometry(QtCore.QRect(900, 550, 600, 31))
        self.time_label.setObjectName("time_label")
        self.time_label.setFont(QFont('DFKai-SB', 20))
        self.label_say = QtWidgets.QLabel(Form)
        self.label_say.setPalette(pe)
        self.label_say.setGeometry(QtCore.QRect(140, 210, 300, 31))
        self.label_say.setObjectName("label_say")
        self.input_label = QtWidgets.QLabel(Form)
        self.input_label.setGeometry(QtCore.QRect(650, 600, 800, 60))
        self.input_label.setObjectName("input_label")
        self.input_label.setText("輸入")
        self.analyis_label = QtWidgets.QLabel(Form)
        self.analyis_label.setGeometry(QtCore.QRect(650, 700, 800, 60))
        self.analyis_label.setObjectName("analyis_label")
        self.analyis_label.setText("解碼")
        self.keyword_label = QtWidgets.QLabel(Form)
        self.keyword_label.setGeometry(QtCore.QRect(40,250, 600, 150))
        self.keyword_label.setObjectName("keyword_label")
        self.keyword_label.setFont(QFont('DFKai-SB', 24))
        self.keyword_label.setPalette(pe)
        self.keyword_label.setText("點餐模式:\n1:單點\n2:數量+餐點(+額外要求)")

        self.Timer=QTimer()
        self.Timer.start()
        self.Timer.timeout.connect(self.timeupdate)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def timeupdate(self):
        
        self.time_label.setText(QDateTime.currentDateTime().toString('yyyy年MM月dd日 hh:mm:ss'))
        if int(QDateTime.currentDateTime().toString('ss'))/5%4==3:
            self.label_2.setPixmap(QtGui.QPixmap("4.png"))
        elif int(QDateTime.currentDateTime().toString('ss'))/5%4==2:
           self.label_2.setPixmap(QtGui.QPixmap("3.png"))
        elif int(QDateTime.currentDateTime().toString('ss'))/5%4==1:
           self.label_2.setPixmap(QtGui.QPixmap("2.png"))
        elif int(QDateTime.currentDateTime().toString('ss'))/5%4==0:
           self.label_2.setPixmap(QtGui.QPixmap("1.png"))
           


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">AI速食點餐對話系統</span></p></body></html>"))
        self.pushButton1.setText(_translate("Form", "點餐"))
        self.menu.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">MENU</span></p></body></html>"))
        self.goal.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">點餐結果</span></p></body></html>"))
